web/config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"

  resources :sessions, only: [:new, :show, :index] do
    resources :requirements
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

web/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

web/app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
end

web/app/models/requirement.rb
class Requirement < ApplicationRecord
  belongs_to :session, foreign_key: :session_uuid, primary_key: :uuid

  normalizes :content, with: -> content { content.strip }

  serialize :erc4ai_classes, type: Array, coder: JSON

  enum :status, { pending: 0, running_classification: 1, classified: 2, error: 3 }

  validates :content, presence: true, length: { maximum: 1000 }

  # Stream to turbo-stream
  after_update_commit { broadcast_update_to "#{session_uuid}/requirements", target: "requirement_#{id}", partial: "requirements/requirement", locals: { requirement: self } }

  def run_binary_classification
    self.ethic = Erc4aiBinaryService.new(content).call.first[:prediction]
    
    Rails.logger.info("Requirement #{id} has been classified as #{ethic}")

    save
  end

  def run_multilabel_classification
    self.erc4ai_classes = Erc4aiMultilabelService.new([content]).call.first&.fetch(:labels, [])
    
    Rails.logger.info("Requirement #{id} has been classified as #{erc4ai_classes}")

    save
  end
end

web/app/models/session.rb
class Session < ApplicationRecord
  self.primary_key = 'uuid'

  has_many :requirements, dependent: :destroy, foreign_key: :session_uuid, primary_key: :uuid

  validates :uuid, presence: true, uniqueness: true

  before_validation :set_uuid, on: :create

  private

  def set_uuid
    self.uuid = SecureRandom.uuid
  end
end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionConcern

  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

web/app/controllers/concerns/session_concern.rb
module SessionConcern
  extend ActiveSupport::Concern

  included do
    before_action :resume_session
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private

  def authenticated?
    resume_session
  end

  def resume_session
    Current.session ||= find_session_by_route || start_new_session
    cookies.signed[:session_uuid] = Current.session.uuid
  end

  def find_session_by_route
    Session.find_by(uuid: params[:session_uuid] || cookies.signed[:session_uuid])
  end

  def start_new_session
    Session.create

  rescue ActiveRecord::RecordNotUnique
    retry
  end
end

web/app/controllers/requirements_controller.rb
class RequirementsController < ApplicationController
  include ActionView::RecordIdentifier # adds `dom_id`

  before_action :set_requirement, only: %i[ show edit update destroy ]

  # GET /requirements or /requirements.json
  def index
    @requirements = requirements
  end

  # GET /requirements/1 or /requirements/1.json
  def show
  end

  # GET /requirements/new
  def new
    @requirement = Requirement.new
  end

  # GET /requirements/1/edit
  def edit
  end

  # POST /requirements or /requirements.json
  def create
    @requirement = Requirement.new(**requirement_params, session: Current.session)

    respond_to do |format|
      if @requirement.save
        run_classification

        format.html { redirect_to session_requirements_path(Current.session, anchor: dom_id(@requirement)) }
        format.json { render :show, status: :created, location: @requirement }
      else
        @requirements = requirements

        format.html { render :index, status: :unprocessable_entity }
        format.json { render json: @requirement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requirements/1 or /requirements/1.json
  def update
    respond_to do |format|
      if @requirement.update(requirement_params)
        format.html { redirect_to [Current.session, @requirement], notice: "Requirement was successfully updated." }
        format.json { render :show, status: :ok, location: @requirement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @requirement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requirements/1 or /requirements/1.json
  def destroy
    @requirement.destroy!

    respond_to do |format|
      format.html { redirect_to session_requirements_path(Current.session), status: :see_other, notice: "Requirement was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_requirement
      @requirement = Requirement.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def requirement_params
      params.expect(requirement: [ :content, :ethic ])
    end

    def requirements
      @requirements = Current.session.requirements.order(created_at: :desc).limit(6)
    end

    def run_classification
      ClassifyRequirementJob.perform_later(@requirement.id, params[:requirement][:classification_type])
    end
end

web/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
    redirect_to new_session_path
  end

  def new
    @session = Current.session

    redirect_to session_requirements_path(@session)
  end

  def show
    @session = Current.session
    redirect_to session_requirements_path(@session)
  end
end

web/app/helpers/application_helper.rb
module ApplicationHelper
end

web/app/helpers/requirements_helper.rb
module RequirementsHelper
end

web/app/helpers/sessions_helper.rb
module SessionsHelper
end

web/app/views/layouts/_banner.html.erb
<div class="w-full md:w-2/3 py-6 my-6 mx-auto relative flex flex-col items-center justify-center rounded-xl bg-gray-900 overflow-hidden">
  <h1 class="text-6xl font-bold text-transparent bg-clip-text animate-gradient">
    ERC4AI
  </h1>

  <!-- Description -->
  <div>
    <p class="text-white text-center mt-5">
      Ethical Requirements Classifier for AI
    </p>
  </div>

  <div class="absolute top-0 left-0 w-full h-full bg-gradient-to-r from-purple-500 via-pink-500 to-indigo-500 opacity-25"></div>
</div>

<div class="w-full md:w-2/3 py-6 my-6 mx-auto bg-white rounded-lg p-9 flex flex-col items-center justify-center">
  <p class="text-center text-lg mt-5">
    ERC4AI is a tool developed to classify software requirements for Artificial Intelligence (AI) systems based on ethical principles. Using Natural Language Processing (NLP) models, it allows both binary classification, determining whether a requirement is related to AI ethics, and multi-label classification, associating requirements with one or more ethical principles.
  </p>
</div>

<style>
@keyframes gradient {
  0% {
    background-position: 0% 50%;
  }
  100% {
    background-position: 100% 50%;
  } 
}

.animate-gradient {
  /* purple to pink to indigo */
  background-image: linear-gradient(90deg, #ad46ff, #615fff, #f6339a, #F43B86, #ad46ff, #615fff, #f6339a, #F43B86, #ad46ff);
  background-size: 200% 200%;
  animation: gradient 4s linear infinite ;
}
</style>

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Web" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/banner" %>

    <main class="container mx-auto mt-13 mb-24 px-5 flex w-full md:w-2/3 mx-auto">
      <%= yield %>
    </main>
  </body>
</html>

web/app/views/requirements/_form.html.erb
<%= form_with(model: [Current.session, requirement], class: "contents") do |form| %>
  <% if requirement.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(requirement.errors.count, "error") %> prohibited this requirement from being saved:</h2>

      <ul class="list-disc ml-6">
        <% requirement.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.text_area :content, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": requirement.errors[:content].none?, "border-red-400 focus:outline-red-600": requirement.errors[:content].any?}] %>
  </div>

  <!-- Radio buttons with the options "Binary Classification" and "Multi Label Classification" -->
  <div class="my-5">
    <div class="flex items-center">
      <div class="mr-3">
        <%= form.radio_button :classification_type, "binary", class: "form-radio h-4 w-4 text-blue-600", checked: true %>
      </div>
      <div>
        <label for="binary" class="font-medium text-gray-700">Binary Classification</label>
      </div>
    </div>

    <div class="flex items-center my-5">
      <div class="mr-3">
        <%= form.radio_button :classification_type, "multilabel", class: "form-radio h-4 w-4 text-blue-600" %>
      </div>
      <div>
        <label for="multilabel" class="font-medium text-gray-700">Multi Label Classification</label>
      </div>
    </div>
  </div>

  <div class="inline">
    <%= form.submit 'Classify Requirement', class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-indigo-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

web/app/views/requirements/_new.html.erb
<div class="w-full p-6">
  <h1 class="font-bold text-3xl">Requirement</h1>

  <%= render "form", requirement: requirement || Requirement.new %>
</div>

web/app/views/requirements/_requirement.html.erb
<%= turbo_stream_from "#{requirement.session_uuid}/requirements" unless requirement.classified? || requirement.error? %>

<%= turbo_frame_tag requirement do %>
  <div id="<%= dom_id requirement %>" class="w-full sm:w-auto space-y-5">
    <div>
      <p class="text-gray-800"><%= requirement.content %></p>
    </div>

    <div class="text-gray-500 text-sm">
      Created <%= time_ago_in_words(requirement.created_at) %> ago
    </div>

    <% if requirement.pending? %>
      <div class="text-gray-500 text-sm w-full bg-gray-100 p-2 rounded-md animate-pulse">
        Awaiting classification
      </div>
    <% elsif requirement.running_classification? %>
      <div class="text-gray-500 text-sm w-full bg-blue-100 p-2 rounded-md flex items-center">
        <svg class="mr-3 -ml-1 size-5 animate-spin text-indigo-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
          <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
          <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
        </svg>
        Running classification
      </div>
    <% elsif requirement.error? %>
      <div class="text-gray-500 text-sm w-full bg-red-100 p-2 rounded-md">
        Classification error
      </div>
    <% end %>

    <% unless requirement.ethic.nil? %>
      <div>
        <% if requirement.ethic? %>
          <span class="px-2 py-1 border-2 border-green-300 rounded-full text-sm text-gray-800">
            Ethical Principle
          </span>
        <% else %>
          <span class="px-2 py-1 border-2 border-red-300 rounded-full text-sm text-gray-800">
            Non-Ethical Principle
          </span>
        <% end %>
      </div>
    <% end %>

    <% if requirement.erc4ai_classes.present? %>
      <div>
        <strong class="block font-medium mb-1">Classes:</strong>

        <div class="flex flex-wrap gap-2">
          <% requirement.erc4ai_classes.each do |erc4ai_class| %>
            <span class="px-2 py-1 border-2 border-gray-300 rounded-full text-sm text-gray-800">
              <%= erc4ai_class %>
            </span>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

web/app/views/requirements/edit.html.erb
<% content_for :title, "Editing requirement" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing requirement</h1>

  <%= render "form", requirement: @requirement %>

  <%= link_to "Show this requirement", [Current.session, @requirement], class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to requirements", session_requirements_path(Current.session), class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

web/app/views/requirements/index.html.erb
<% content_for :title, "Requirements" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block w-full" id="notice"><%= notice %></p>
  <% end %>

  <div class="w-full bg-white shadow-lg rounded-lg p-6 mb-5">
    <%= render "requirements/new", requirement: @requirement || Requirement.new %>
  </div>

  <turbo-frame id="requirements">
    <% if @requirements.any? %>
      <div class="bg-white shadow-lg rounded-lg p-9">
        <div class="flex justify-between items-center">
          <h1 class="font-bold text-3xl">Last Requirements</h1>
        </div>

        <div id="requirements" class="grid grid-cols-1 lg:grid-cols-3 gap-5 py-6">
          <% @requirements.each do |requirement| %>
            <div class="relative border-1 border-gray-400 rounded-lg p-6">
              <%= render requirement %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </turbo-frame>
</div>

web/app/views/requirements/new.html.erb
<% content_for :title, "New requirement" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New requirement</h1>

  <%= render "form", requirement: @requirement %>

  <%= link_to "Back to requirements", session_requirements_path(Current.session), class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

web/app/views/requirements/show.html.erb
<% content_for :title, "Showing requirement" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing requirement</h1>

  <%= render @requirement %>

  <%= link_to "Edit this requirement", edit_session_requirement_path(Current.session, @requirement), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to requirements", session_requirements_path(Current.session), class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="sm:inline-block mt-2 sm:mt-0 sm:ml-2">
    <%= button_to "Destroy this requirement", [Current.session, @requirement], method: :delete, class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
  </div>
</div>